language: php

php: 7.1

install:
    - composer update

script:
    # check Coding Standard
    - vendor/bin/ecs check bin src
    # check PHPStan
    #- vendor/bin/phpstan analyse bin src --level max
    # test that website is generated
    - vendor/bin/statie generate source
    # re-build website when on master only
    - |
      if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
          vendor/bin/statie push-to-github jangalek/jangalek.github.io --token=${GH_TOKEN}
          # tweet new posts, if any
          # bin/tweet-new-posts
      fi
notifications:
    email: never

env:
    global:
        # Go to: Gitub User => Settings => Personal Access Token => Generate New Token
        # Select "Repo" scope

        # Download Travis CLI tool locally: https://github.com/travis-ci/travis.rb#installation
        # Run in shell in repository root: travis encrypt GH_TOKEN=<code>

        # If repo is not recognized by travis api, go to https://travis-ci.org/<repository-slug>, like githu.com/<repository-slug>
        # And add it there; like you do when you want to run tests on some repository
        - secure: "sYRDL98B7gAgeYGK1dOZDiAuhgQEId8Bg+LLaBDYh03m6WlPcuIsQ8lexSnELbFni49dmxTuHdnacY8mJP9gd0qcmf2Whm+t8TAseUVpcu5lTN6IKeNlNL0E62/ZS6zlfs9xdJoHX8fDTXtZdHBUSpeIEtN8wKUUDmUFpAxzKR2RMd0qSiICSif4waePk7rDw1sNbiB2TiVft002/ozA26cW4GiYnBWbcfcKwZ8D7kjCplBkWaSKiXN3KISTUFKSWEnHkQAI7WhjWUx3TzPJpUMEUtWk05WvJqk1GeS+yiXt7B+oKitO6QAOtJ/DsMbjxZ6pqKAwWW3gMqVpoqJFPZCH2Ufmv3ckYtprSt+yTPEyCOYSpMHf+HBswfTN1VSHIXLz1E1ZzBir8dIDeZm+07ixM5FenrUzWvAxxhHFQC/l+AbGJDGgqw83vmFq2hWHKz5dKRhql+Q77dH9NozJ7p1EauqDfuG7SQy6JbZ3ORde4YjdA8zh9zntJz2CV1FJCYc/yDyALB5BxVIaQ6caUMdsiFtRpfEbFP21n6UDam6SV7IgmEKcpNOpIOtxhy8YHvij1iuRs+4ltNGubzkXFvHfafxj9Wm9Mbi8Ng4KB9m5LnmGvxLWEIjThPCxjoGbNJvjer7uowL0CuF35uHaYnfPFrH/VTWhl1bU9t+GY4Q="

        # Travis API for TweetPublisher
        #- secure: "ptIeVx1hGjW2+O5cxm0sisMixdXqJpp/PxXJ3WLlpTo7ApQHInvmHABb3DmnPqekSARipyEnjc/REHJGut7Z0lXS2jK8X0nI0lKv+s28rN5MDG9h5F6aj4xOo3II39Vc/sHdEWhXy5guGVX4thiHqggAZqMKRSljXtD+KwgLI/cB+OKi+E6rQbbD93BStoiGJR2SHsqB+t5GmjU8dF5vU4IBqmb1WmaJeqDyYRBcA7IPtim8fMB8AxbA95M1KfH1xXZcQcFM2+fSRDjnniLAfatoYPrvDB+RpadYj8KbIucKqOTKSD7tgck3WS6zf/qxEVJ35AqnS09vAqUQjJatKHsIMulnriUWGA9zPMN4j5GkuaaE+2YEFj5W+gIFDNL/rB8OiKdvyzG9Ggs3kBEGFgHRsEsnATdcblNkjxmXohCvZZWmLt//D+kAcExt4XEFSHBLNAVmx0afW9P1pEkDhb8Hqsd+nhIbINYUvElATbapMdy8l9oTiq+0XcooDz6ebjYXNsZYP4VrAa2K2fgxtbDHdcPdmTw++sRJbaZU9fu8lScxzz3MHC2vniP3GNzMXiRyyGzbWDQJWjfV9EGapD+bwwcl+Z0jxQvvtBQS2L2TRq6QUJh4BmOT0ovemkXeMpHTyn+/JmhF3J85nVOGzwH9cILWw/jy/b2/FGGogwI="

        #- secure: "l3od1epduiXpgBHVfxarQrZUrwvSqQ5zCbPRCkTrobe8YWVXNPnuRFgtd/4UuFhig2Z1L9mXnymCoJ+iWsPJqDcCXLx6Ixp6Ss3xMQtdS8AvWPvfFnVjRUFcVzCPXGgtu7/OrIsh8xQT0AS9gU82Nv6ToMdKRDwGVeof1PlfGiBMb38BFbb1GGbdvlCQM7kU7Oph30TArlRrtHGhEbv5AM0HzXtHuf8tpaqZ6UKMRnm0Rvt1nIgulcFos9PFv10O3NSchhSnUiUYALbLnANxouazgUihE0pzcg9r1+TOy20BEgEw9pQstD6RRbUbX7mfYpS9GtEcIE8ZwT7p700pafNvVmFr3rr093W+Yelng+G7ur7oTl0l9934zBTIO72irJrHKxXlQx0Z9RGVtO3owFB/Hv9RSfQronz2sNk6bpeX6fVg47zFenqJsIsHDQUCox2h5GoKchjN2gXjnrQfsmx4toH7ujuD5j+QJbNgqajz4g9snKpX0nFG3zSVWFZod8MyzHdlXDAftufoNFaYe0Li6tEjCYHCXEsyppjfh2U7Y6R3iEtOHycr+rWfdjHBaq8xL8GG/mQJefmsSHvGpls6980sL4aI2UkupmYgH/TdUGu8SIhRmQh7BAdxWZaHF5PjbNRrQJheshXzTCMhmOWaLq0PrkukOa1+IFVZX38="

        #- secure: "YGh7Br8Wn4zROWHD7LLlj1K03KNyOuM26IluWqoVgEFDW96vEt5b44yjBQMXs5hsroEiXzlrJtqrRdS3Br6E8pACcx3oi92UhdrGifUHNM2J5QosJnmou2XvsuYziJQFS7RN4Zdfl4/EgBtRKWq1U89S76GvqhIk5B4LSgZpQlEGLn9+8IdfihrDst0SF+ok8Ja5W4uHpXX34r53lBYAyJxCMSFP+gseHBgMHCu/b0w3IVInSgEt0HeobPibG9+jci5xzsWVBC5sZZwId6q/zFqP8fSYmSN0ZFkKotJGKeHpvmnW5qu616C40x8ugv6lqyWkrFFqc1bqjS7/9Bq7/Gzn+ukwvGBXuewUEmca980zT2AZrgaJt1Dn3bG7lsmTbph/tU00SSq0JECKzYoYBwYKA1ZUNSGIPLNE5G4I9FSIMYp/L5DRBLn7MGkUXcju6ArdYHm7+n3Iilp0DQ2OWns5o0PvfG+AU9UZzc1bua8lOlGPjfs+IfD260x4Yb1VZJIw75wpKhm1lspOzxNkTF3EgWo406rN7WtWv33lgfTSwG/LJ/X5OHSa06Kdaa1KJrhMbw+umNbgYQyDu607yy7zaF0MtB7y87KfhEx18i8/uxlJBGiHyPdVAN8r5vO7tOpgBzWZtaGKMNbPKEvoBpKCtO9B5o27ngkwNjo+pKM="

        #- secure: "mu94wwufIDyiHiYyVmeDpM+VStR1k1DXguURmCtO+vVD626D3pksfJO+v1Sh4RSIVF2OsKo0SFE0qE6ET8K4xk/lDz9K91Qi5uA76oFKGcOR0D6ZbmrA1UKF3OlI6tLKs1/shj/zylVBKr8ATf9z4txr/tHH/S+VYyJKnISo/Ardl6ko6VLwplDdLSk2QIfxFBo43Mc0NP4TqZj6oM2EqL/CW4OOw7bOj9cjgBfFZ463WWFnHBZSrgapDSQdhanNza15hOeVIUDUHBtNGe346e6HRCTCI/ynnWi8xwxcO9f3dGpfr36dRcPIfXXmAyNg+OzGHY/Z5Br5LPyk7MdtSf496xVWhrX0wcrzQwYL6weZeNVe3DMfgiXB4db9ixDElqZ1UN1V9WmKkYLLRqubYWRvqch1pVWmlh7C/b5paGEvPo3OPR6Mizsa8OZhhVC24VBz19XAFmFi/HJtd4beLosWg7fR72OMgJQl88b6BYDhV8hHLkp7Ut4/RCY/i78qaXks1i4FwHDEY97wciXmGwFeZdUJtIk39oej1SfZUsJ8W+mtX1zhi5nZVGAlo/tF56QYDtCdZItGXjcuupFn+sxtg3PPna1eeBYgXuiv0mZEqjfELLIZ12VAbp8ZpYlIuaUJlboPfjmfh1xHgnD6HxllAVx5UFs1szFoi4ogyyM="
